plugins {
    id 'java'
}

dependencies {
    api project(':dot4j')
    api project(':property-framework')
    testImplementation 'org.junit.jupiter:junit-jupiter-api:6.1.3'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:6.1.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.3'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
    }
}



group = 'dev.skidfuscator.mapleir'
description = 'MapleIR-stdlib'

tasks.register('testsJar', Jar) {
    archiveClassifier = 'tests'
    from(sourceSets.test.output)
}

